version: '3'
services:
  forkthis-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unati-backend
    ports:
      - "3010:3010"  
    depends_on:
      - mongo-db  

  mongo-db:
    image: mongo:latest 
    container_name: mongo-container-unati
    ports:
      - "27018:27018"
    command: --port 27018
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:
    name: mongo-data-forkthis
    driver: local